[2024-11-05T18:11:15.242+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T18:11:13.601984+00:00 [queued]>
[2024-11-05T18:11:15.252+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T18:11:13.601984+00:00 [queued]>
[2024-11-05T18:11:15.253+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T18:11:15.282+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): load_data> on 2024-11-05 18:11:13.601984+00:00
[2024-11-05T18:11:15.291+0000] {standard_task_runner.py:57} INFO - Started process 236 to run task
[2024-11-05T18:11:15.294+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'load_data', 'manual__2024-11-05T18:11:13.601984+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmpet0yeile']
[2024-11-05T18:11:15.295+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask load_data
[2024-11-05T18:11:15.349+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.load_data manual__2024-11-05T18:11:13.601984+00:00 [running]> on host 697ad0dc81ee
[2024-11-05T18:11:15.432+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T18:11:13.601984+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T18:11:13.601984+00:00'
[2024-11-05T18:11:15.433+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T18:11:15.433+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T18:11:15.445+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T18:11:15.511+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T18:11:15.512+0000] {ssh.py:478} INFO - Running command: /opt/hadoop-3.2.1/bin/hdfs dfs -mkdir /data && /opt/hadoop-3.2.1/bin/hdfs dfs -copyFromLocal /data/sprogrami2016.csv /data && /opt/hadoop-3.2.1/bin/hdfs dfs -ls
[2024-11-05T18:11:15.606+0000] {ssh.py:529} WARNING - ERROR: JAVA_HOME is not set and could not be found.
[2024-11-05T18:11:15.634+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-11-05T18:11:15.637+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_initial_data, task_id=load_data, execution_date=20241105T181113, start_date=20241105T181115, end_date=20241105T181115
[2024-11-05T18:11:15.648+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task load_data (SSH operator error: exit status = 1; 236)
[2024-11-05T18:11:15.666+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T18:11:15.685+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
