[2024-11-05T20:07:56.496+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [queued]>
[2024-11-05T20:07:56.505+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [queued]>
[2024-11-05T20:07:56.505+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-11-05T20:07:56.516+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2024-11-05 20:03:47.889841+00:00
[2024-11-05T20:07:56.524+0000] {standard_task_runner.py:57} INFO - Started process 421 to run task
[2024-11-05T20:07:56.527+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'initial_transform', 'transform', 'manual__2024-11-05T20:03:47.889841+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/initial_transform.py', '--cfg-path', '/tmp/tmpkaar104u']
[2024-11-05T20:07:56.528+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask transform
[2024-11-05T20:07:56.583+0000] {task_command.py:416} INFO - Running <TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [running]> on host 02af4744f5fd
[2024-11-05T20:07:56.668+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initial_transform' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T20:03:47.889841+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T20:03:47.889841+00:00'
[2024-11-05T20:07:56.681+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:07:56.681+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:07:56.778+0000] {hive.py:475} INFO - USE `default`
[2024-11-05T20:07:56.884+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:07:56.884+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:07:56.953+0000] {hive.py:475} INFO - USE `default`
[2024-11-05T20:07:57.041+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:07:57.041+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:07:57.041+0000] {hive.py:475} INFO - set ***.ctx.dag_id=initial_transform
[2024-11-05T20:07:57.044+0000] {hive.py:475} INFO - set ***.ctx.task_id=transform
[2024-11-05T20:07:57.046+0000] {hive.py:475} INFO - set ***.ctx.execution_date=2024-11-05T20:03:47.889841+00:00
[2024-11-05T20:07:57.049+0000] {hive.py:475} INFO - set ***.ctx.try_number=3
[2024-11-05T20:07:57.052+0000] {hive.py:475} INFO - set ***.ctx.dag_run_id=manual__2024-11-05T20:03:47.889841+00:00
[2024-11-05T20:07:57.055+0000] {hive.py:475} INFO - set ***.ctx.dag_owner=***
[2024-11-05T20:07:57.058+0000] {hive.py:475} INFO - set ***.ctx.dag_email=
[2024-11-05T20:07:57.061+0000] {hive.py:475} INFO - select * from invites
[2024-11-05T20:07:57.181+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/initial_transform.py", line 22, in transform
    res = hive_hook.to_csv('select * from invites', 'data/output.csv')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/hive/hooks/hive.py", line 979, in to_csv
    with open(csv_filepath, "w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/output.csv'
[2024-11-05T20:07:57.193+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=initial_transform, task_id=transform, execution_date=20241105T200347, start_date=20241105T200756, end_date=20241105T200757
[2024-11-05T20:07:57.205+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task transform ([Errno 2] No such file or directory: 'data/output.csv'; 421)
[2024-11-05T20:07:57.221+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T20:07:57.242+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
