[2024-11-05T20:08:16.629+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [queued]>
[2024-11-05T20:08:16.636+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [queued]>
[2024-11-05T20:08:16.636+0000] {taskinstance.py:1361} INFO - Starting attempt 4 of 4
[2024-11-05T20:08:16.646+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2024-11-05 20:03:47.889841+00:00
[2024-11-05T20:08:16.654+0000] {standard_task_runner.py:57} INFO - Started process 430 to run task
[2024-11-05T20:08:16.657+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'initial_transform', 'transform', 'manual__2024-11-05T20:03:47.889841+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/initial_transform.py', '--cfg-path', '/tmp/tmp2vuyuley']
[2024-11-05T20:08:16.658+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask transform
[2024-11-05T20:08:16.708+0000] {task_command.py:416} INFO - Running <TaskInstance: initial_transform.transform manual__2024-11-05T20:03:47.889841+00:00 [running]> on host 02af4744f5fd
[2024-11-05T20:08:16.794+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initial_transform' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T20:03:47.889841+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T20:03:47.889841+00:00'
[2024-11-05T20:08:16.808+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:08:16.809+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:08:16.899+0000] {hive.py:475} INFO - USE `default`
[2024-11-05T20:08:16.978+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:08:16.978+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:08:17.059+0000] {hive.py:475} INFO - USE `default`
[2024-11-05T20:08:17.137+0000] {connection.py:232} WARNING - Connection schemes (type: hive_cli) shall not contain '_' according to RFC3986.
[2024-11-05T20:08:17.137+0000] {base.py:73} INFO - Using connection ID 'beeline_conn' for task execution.
[2024-11-05T20:08:17.137+0000] {hive.py:475} INFO - set ***.ctx.dag_id=initial_transform
[2024-11-05T20:08:17.140+0000] {hive.py:475} INFO - set ***.ctx.task_id=transform
[2024-11-05T20:08:17.143+0000] {hive.py:475} INFO - set ***.ctx.execution_date=2024-11-05T20:03:47.889841+00:00
[2024-11-05T20:08:17.145+0000] {hive.py:475} INFO - set ***.ctx.try_number=4
[2024-11-05T20:08:17.147+0000] {hive.py:475} INFO - set ***.ctx.dag_run_id=manual__2024-11-05T20:03:47.889841+00:00
[2024-11-05T20:08:17.149+0000] {hive.py:475} INFO - set ***.ctx.dag_owner=***
[2024-11-05T20:08:17.152+0000] {hive.py:475} INFO - set ***.ctx.dag_email=
[2024-11-05T20:08:17.155+0000] {hive.py:475} INFO - select * from invites
[2024-11-05T20:08:17.298+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/initial_transform.py", line 22, in transform
    res = hive_hook.to_csv('select * from invites', 'data/output.csv')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/hive/hooks/hive.py", line 979, in to_csv
    with open(csv_filepath, "w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/output.csv'
[2024-11-05T20:08:17.312+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=initial_transform, task_id=transform, execution_date=20241105T200347, start_date=20241105T200816, end_date=20241105T200817
[2024-11-05T20:08:17.327+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task transform ([Errno 2] No such file or directory: 'data/output.csv'; 430)
[2024-11-05T20:08:17.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T20:08:17.372+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
