[2024-11-05T14:55:44.386+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:55:30.096134+00:00 [queued]>
[2024-11-05T14:55:44.394+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:55:30.096134+00:00 [queued]>
[2024-11-05T14:55:44.394+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-11-05T14:55:44.404+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): name_node_task> on 2024-11-05 14:55:30.096134+00:00
[2024-11-05T14:55:44.411+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2024-11-05T14:55:44.415+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'initial_dag', 'name_node_task', 'manual__2024-11-05T14:55:30.096134+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/initial-dag.py', '--cfg-path', '/tmp/tmpjl7vac3b']
[2024-11-05T14:55:44.416+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask name_node_task
[2024-11-05T14:55:44.474+0000] {task_command.py:416} INFO - Running <TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:55:30.096134+00:00 [running]> on host b7124ba1e092
[2024-11-05T14:55:44.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initial_dag' AIRFLOW_CTX_TASK_ID='name_node_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T14:55:30.096134+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T14:55:30.096134+00:00'
[2024-11-05T14:55:44.566+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T14:55:44.566+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T14:55:44.575+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T14:55:44.639+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T14:55:44.640+0000] {ssh.py:478} INFO - Running command: ls && ls -al && pwd && ls /data -al"
[2024-11-05T14:55:44.695+0000] {ssh.py:529} WARNING - bash: -c: line 0: unexpected EOF while looking for matching `"'
[2024-11-05T14:55:44.696+0000] {ssh.py:529} WARNING - bash: -c: line 1: syntax error: unexpected end of file
[2024-11-05T14:55:44.726+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-11-05T14:55:44.729+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=initial_dag, task_id=name_node_task, execution_date=20241105T145530, start_date=20241105T145544, end_date=20241105T145544
[2024-11-05T14:55:44.741+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task name_node_task (SSH operator error: exit status = 1; 113)
[2024-11-05T14:55:44.787+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T14:55:44.807+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
