[2024-11-05T17:33:08.738+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.name_node_task manual__2024-11-05T17:33:06.630619+00:00 [queued]>
[2024-11-05T17:33:08.746+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.name_node_task manual__2024-11-05T17:33:06.630619+00:00 [queued]>
[2024-11-05T17:33:08.747+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T17:33:08.758+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): name_node_task> on 2024-11-05 17:33:06.630619+00:00
[2024-11-05T17:33:08.767+0000] {standard_task_runner.py:57} INFO - Started process 145 to run task
[2024-11-05T17:33:08.770+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'name_node_task', 'manual__2024-11-05T17:33:06.630619+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmpm6ej03nb']
[2024-11-05T17:33:08.771+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask name_node_task
[2024-11-05T17:33:08.823+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.name_node_task manual__2024-11-05T17:33:06.630619+00:00 [running]> on host 2eb52e8f0573
[2024-11-05T17:33:08.907+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='name_node_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T17:33:06.630619+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T17:33:06.630619+00:00'
[2024-11-05T17:33:08.908+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T17:33:08.908+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T17:33:08.923+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T17:33:08.993+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T17:33:08.994+0000] {ssh.py:478} INFO - Running command: hdfs dfs ls
[2024-11-05T17:33:09.058+0000] {ssh.py:529} WARNING - bash: hdfs: command not found
[2024-11-05T17:33:09.089+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2024-11-05T17:33:09.091+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_initial_data, task_id=name_node_task, execution_date=20241105T173306, start_date=20241105T173308, end_date=20241105T173309
[2024-11-05T17:33:09.102+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task name_node_task (SSH operator error: exit status = 127; 145)
[2024-11-05T17:33:09.143+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T17:33:09.169+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
