[2024-11-05T17:46:23.251+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T17:38:21.610853+00:00 [queued]>
[2024-11-05T17:46:23.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T17:38:21.610853+00:00 [queued]>
[2024-11-05T17:46:23.260+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-11-05T17:46:23.269+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): load_data> on 2024-11-05 17:38:21.610853+00:00
[2024-11-05T17:46:23.278+0000] {standard_task_runner.py:57} INFO - Started process 337 to run task
[2024-11-05T17:46:23.281+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'load_data', 'manual__2024-11-05T17:38:21.610853+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmpl44ld6rl']
[2024-11-05T17:46:23.283+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask load_data
[2024-11-05T17:46:23.336+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.load_data manual__2024-11-05T17:38:21.610853+00:00 [running]> on host 2eb52e8f0573
[2024-11-05T17:46:23.424+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T17:38:21.610853+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T17:38:21.610853+00:00'
[2024-11-05T17:46:23.424+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T17:46:23.424+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T17:46:23.432+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T17:46:23.533+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T17:46:23.534+0000] {ssh.py:478} INFO - Running command: /root/hdfs dfs -mkdir /data && /root/hdfs dfs -copyFromLocal /data/sprogrami2016.csv /data && /root/hdfs dfs -ls
[2024-11-05T17:46:23.587+0000] {ssh.py:529} WARNING - bash: /root/hdfs: No such file or directory
[2024-11-05T17:46:23.616+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2024-11-05T17:46:23.619+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_initial_data, task_id=load_data, execution_date=20241105T173821, start_date=20241105T174623, end_date=20241105T174623
[2024-11-05T17:46:23.629+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task load_data (SSH operator error: exit status = 127; 337)
[2024-11-05T17:46:23.653+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T17:46:23.681+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
