[2024-11-05T19:45:45.350+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T19:44:14.090358+00:00 [queued]>
[2024-11-05T19:45:45.359+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T19:44:14.090358+00:00 [queued]>
[2024-11-05T19:45:45.360+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-11-05T19:45:45.369+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): load_data> on 2024-11-05 19:44:14.090358+00:00
[2024-11-05T19:45:45.377+0000] {standard_task_runner.py:57} INFO - Started process 117 to run task
[2024-11-05T19:45:45.380+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'load_data', 'manual__2024-11-05T19:44:14.090358+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmpfay0cd5z']
[2024-11-05T19:45:45.381+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load_data
[2024-11-05T19:45:45.436+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.load_data manual__2024-11-05T19:44:14.090358+00:00 [running]> on host 02af4744f5fd
[2024-11-05T19:45:45.515+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T19:44:14.090358+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T19:44:14.090358+00:00'
[2024-11-05T19:45:45.515+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T19:45:45.515+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T19:45:45.523+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T19:45:45.579+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T19:45:45.580+0000] {ssh.py:478} INFO - Running command: /opt/hadoop-3.2.1/bin/hdfs dfs -mkdir /data && /opt/hadoop-3.2.1/bin/hdfs dfs -copyFromLocal /data/sprogrami2016.csv /data && /opt/hadoop-3.2.1/bin/hdfs dfs -ls /data
[2024-11-05T19:45:48.529+0000] {ssh.py:529} WARNING - 2024-11-05 19:45:48,528 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2024-11-05T19:45:50.167+0000] {ssh.py:524} INFO - Found 1 items
[2024-11-05T19:45:50.167+0000] {ssh.py:524} INFO - -rw-r--r--   3 root supergroup     703903 2024-11-05 19:45 /data/sprogrami2016.csv
[2024-11-05T19:45:50.664+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_initial_data, task_id=load_data, execution_date=20241105T194414, start_date=20241105T194545, end_date=20241105T194550
[2024-11-05T19:45:50.724+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-05T19:45:50.740+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
